### ISSUE TITLE
Admin panel :: Feature request

### ISSUE THREAD

**Issue by ghost** [sander3/laravel-magic-auth#10]
Hi @sander3,

Thank you for publishing this.
Is there a possibility of you adding a admin panel where you can delete users and so something like the image below:

![631adf40-ba5b-11e6-9ea1-7fc614a45f28](https://user-images.githubusercontent.com/55157226/67209386-8b4cc480-f417-11e9-9fdf-a8071243b7f5.png)
![631a3d74-ba5b-11e6-85aa-4a3e53656a6d](https://user-images.githubusercontent.com/55157226/67209385-8b4cc480-f417-11e9-8cdf-e93b0c95d7c3.png)

**Comment by ghost** [comment]
Or perhaps have a example of this implemented somewhere with admin functionality I would greatly appreciate that.

**Comment by sander3** [comment]
Hi there,

This feature is out-of-scope. `laravel-magic-auth` focuses on the authentication logic only. User management (and other CRUDs) should be handled on the application level.
