### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by ghost** [sander3/laravel-magic-auth#11]
Hi @sander3,

Where can I find a demo or example of this implemented I am just learning php and laravel and would love to have something like this built in my app.

**Comment by sander3** [comment]
Hi there,

You can find an example implementation here: https://github.com/sander3/tenancy/commit/215591968ff13368b6a6843bee863c44e9328cd7
Beware, it's somewhat outdated. The principles used in the implementation itself however, remain the same.

**Comment by ghost** [comment]
Thank you @sander3
